In [2]:
import pandas as pd 
df = pd.DataFrame({"Brand": ["Tata","BMW","Toyota", "VW"]})
df

    Brand
0    Tata
1     BMW
2  Toyota
3      VW

In [4]:
df.shape

(4, 1)

In [3]:
encoded_df = pd.get_dummies(df , columns=["Brand"])
encoded_df

   Brand_BMW  Brand_Tata  Brand_Toyota  Brand_VW
0      False        True         False     False
1       True       False         False     False
2      False       False          True     False
3      False       False         False      True

In [5]:
encoded_df.shape

(4, 4)